#! /bin/sh -e
# This file is automatically generated with: tup generate build.sh bin/jamb
export tup_vardict="$(cd $(dirname $0) && pwd)/tup-generate.vardict"
(bash codegen-defaultConfig.sh > build/Launchpad-defaultConfig.hh)
(c++ -g -std=c++20 -I/usr/src/googletest/googletest/include -Igenerated -c src/Aeolus.cc -o build/Aeolus.o)
(c++ -g -std=c++20 -I/usr/src/googletest/googletest/include -Igenerated -c src/Command.cc -o build/Command.o)
(c++ -g -std=c++20 -I/usr/src/googletest/googletest/include -Igenerated -c src/Jamb.cc -o build/Jamb.o)
(c++ -g -std=c++20 -I/usr/src/googletest/googletest/include -Igenerated -c src/Launchpad.cc -o build/Launchpad.o)
(c++ -g -std=c++20 -I/usr/src/googletest/googletest/include -Igenerated -c src/test/FakeMidi.cc -o build/test/FakeMidi.o)
(c++ -g -std=c++20 -I/usr/src/googletest/googletest/include -Igenerated -c src/linux/ASeq.cc -o build/linux/ASeq.o)
(c++ -g -std=c++20 -I/usr/src/googletest/googletest/include -Igenerated -c src/linux/main.cc -o build/linux/main.o)
(c++ -g -std=c++20 -I/usr/src/googletest/googletest/include -Igenerated build/Aeolus.o build/Command.o build/Jamb.o build/Launchpad.o build/linux/ASeq.o build/linux/main.o build/test/FakeMidi.o -lgtest -lasound -lfmt -lpthread -lyaml-cpp -o bin/jamb)
