#! /bin/sh -e
# This file is automatically generated with: tup generate build.sh linux/jamb
export tup_vardict="$(cd $(dirname $0) && pwd)/tup-generate.vardict"
mkdir -p "generated"
(bash codegen-defaultConfig.sh > generated/Launchpad-defaultConfig.hh)
(c++ -g -std=c++20 -I/usr/src/googletest/googletest/include -Igenerated -c Aeolus.cc -o Aeolus.o)
(c++ -g -std=c++20 -I/usr/src/googletest/googletest/include -Igenerated -c Command.cc -o Command.o)
(c++ -g -std=c++20 -I/usr/src/googletest/googletest/include -Igenerated -c Jamb.cc -o Jamb.o)
(c++ -g -std=c++20 -I/usr/src/googletest/googletest/include -Igenerated -c Launchpad.cc -o Launchpad.o)
(c++ -g -std=c++20 -I/usr/src/googletest/googletest/include -Igenerated -c test/FakeMidi.cc -o test/FakeMidi.o)
(c++ -g -std=c++20 -I/usr/src/googletest/googletest/include -Igenerated -c linux/ASeq.cc -o linux/ASeq.o)
(c++ -g -std=c++20 -I/usr/src/googletest/googletest/include -Igenerated -c linux/main.cc -o linux/main.o)
(c++ -g -std=c++20 -I/usr/src/googletest/googletest/include -Igenerated Aeolus.o Command.o Jamb.o Launchpad.o linux/ASeq.o linux/main.o test/FakeMidi.o -lgtest -lasound -lfmt -lpthread -lyaml-cpp -o linux/jamb)
