#! /bin/sh -e
# This file is automatically generated with: tup generate build.sh bin/jamb
export tup_vardict="$(cd $(dirname $0) && pwd)/tup-generate.vardict"
mkdir -p "bin"
mkdir -p "build"
mkdir -p "build/linux"
(bash codegen-defaultConfig.sh > build/Launchpad-defaultConfig.hh)
(c++ -g -std=c++20 -I/usr/src/googletest/googletest/include -Ibuild -c src/Aeolus.cc -o build/Aeolus.o)
(c++ -g -std=c++20 -I/usr/src/googletest/googletest/include -Ibuild -c src/Command.cc -o build/Command.o)
(c++ -g -std=c++20 -I/usr/src/googletest/googletest/include -Ibuild -c src/Jamb.cc -o build/Jamb.o)
(c++ -g -std=c++20 -I/usr/src/googletest/googletest/include -Ibuild -c src/Launchpad.cc -o build/Launchpad.o)
(c++ -g -std=c++20 -I/usr/src/googletest/googletest/include -Ibuild -c src/linux/ASeq.cc -o build/linux/ASeq.o)
(c++ -g -std=c++20 -I/usr/src/googletest/googletest/include -Ibuild -c src/linux/main.cc -o build/linux/main.o)
(c++ -g -std=c++20 -I/usr/src/googletest/googletest/include -Ibuild build/Aeolus.o build/Command.o build/Jamb.o build/Launchpad.o build/linux/ASeq.o build/linux/main.o -lgtest -lasound -lfmt -lpthread -lyaml-cpp -o bin/jamb)
